application: pzeevrouw
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|css|gif|png|jpg|svg|js|ico))$
  static_files: \1
  upload: .+\.(html|css|gif|png|jpg|svg|js|ico)$
  application_readable: true

- url: /.*
  static_files: index.html
  upload: index.html
  application_readable: true